name: Markdown CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Building the Solution
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        dotnet: [ '3.1.200' ]
    steps:
    - name: Checkout Workspace
      uses: actions/checkout@v2

    - name: Setup .net ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Build Markdoc.sln
      run: sh ./build.sh
